Add release phase and remove redirect/test server and bin/release

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -39,35 +39,28 @@ export BUILD_DIR=$1
 DRIVER_VERSION="1.0.0-DEMO-6"
 BUILD_TOOL_URL=https://github.com/forcedotcom/force-com-buildpack/releases/download/$DRIVER_VERSION/driver-prototype.jar
 JAR_NAME=appcloud-client.jar
-CLIENT_DIR=lib
-BUILD_TOOL_DEST=$BUILD_DIR/$CLIENT_DIR
+SALESFORCE_DIR=$BUILD_DIR/.salesforce
+BUILD_TOOL_DEST=$SALESFORCE_DIR/lib
 BUILD_TOOL_JAR=$BUILD_TOOL_DEST/$JAR_NAME
 
 mkdir -p $BUILD_TOOL_DEST
 echo "-----> Downloading Force.com test client version $DRIVER_VERSION"
 wget -q $BUILD_TOOL_URL -O $BUILD_TOOL_JAR
 
-# figure out the source version and write it to a file to be used in runtime
-echo "$SOURCE_VERSION" > $BUILD_TOOL_DEST/SOURCE_VERSION
 
-# write out testrunner script
-mkdir -p $BUILD_DIR/bin
-cp lib/server.py $BUILD_DIR/$CLIENT_DIR/server.py
+echo "-----> Setting up Force.com for release phase deployment."
 
-cat > $BUILD_DIR/bin/runtests << EOF
-
-export SOURCE_VERSION=\$(< $CLIENT_DIR/SOURCE_VERSION)
-java -cp $CLIENT_DIR/$JAR_NAME TestRunner &
-python $CLIENT_DIR/server.py
+cat > $SALESFORCE_DIR/deploy << EOF
+if [[ \$SALESFORCE_URL ]]
+then
+  echo "Deploying Force.com application"
+  java -cp .salesforce/lib/$JAR_NAME Main 
+else
+  echo "Force.com deployment failed because SALESFORCE_URL is not configured"
+  exit 1
+fi
 EOF
 
-chmod +x $BUILD_DIR/bin/runtests
+chmod +x $SALESFORCE_DIR/deploy
 
-
-if [[ $SALESFORCE_URL ]]
-then
-  echo "-----> Deploying Force.com application"
-  java -cp $BUILD_TOOL_JAR Main | indent
-else
-  echo "-----> Skipping Force.com deployment because SALESFORCE_URL was not configured"
-fi
+echo "Configure your application to invoke .salesforce/deploy in your release phase script." | indent
